global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  # Scrape Prometheus metrics (itself)
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    labels:
      app: "prometheus"

  - job_name: 'jenkins'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'docker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9323']  # Docker Exporter for Prometheus

    labels:
      app: "docker"
